//go:build !codegen

// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package queryresult

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

func (t *QueryResult) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)
	fieldCount := 1

	if t.Result0_1 == nil {
		fieldCount--
	}

	if _, err := cw.Write(cbg.CborEncodeMajorType(cbg.MajMap, uint64(fieldCount))); err != nil {
		return err
	}

	// t.Result0_1 (queryresult.QueryResult0_1) (struct)
	if t.Result0_1 != nil {

		if len("index/query/result@0.1") > 8192 {
			return xerrors.Errorf("Value in field \"index/query/result@0.1\" was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("index/query/result@0.1"))); err != nil {
			return err
		}
		if _, err := cw.WriteString(string("index/query/result@0.1")); err != nil {
			return err
		}

		if err := t.Result0_1.MarshalCBOR(cw); err != nil {
			return err
		}
	}
	return nil
}

func (t *QueryResult) UnmarshalCBOR(r io.Reader) (err error) {
	*t = QueryResult{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("QueryResult: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 22)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Result0_1 (queryresult.QueryResult0_1) (struct)
		case "index/query/result@0.1":

			{

				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}
					t.Result0_1 = new(QueryResult0_1)
					if err := t.Result0_1.UnmarshalCBOR(cr); err != nil {
						return xerrors.Errorf("unmarshaling t.Result0_1 pointer: %w", err)
					}
				}

			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *QueryResult0_1) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{162}); err != nil {
		return err
	}

	// t.Claims ([]cid.Cid) (slice)
	if len("claims") > 8192 {
		return xerrors.Errorf("Value in field \"claims\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("claims"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("claims")); err != nil {
		return err
	}

	if len(t.Claims) > 8192 {
		return xerrors.Errorf("Slice value in field t.Claims was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Claims))); err != nil {
		return err
	}
	for _, v := range t.Claims {

		if err := cbg.WriteCid(cw, v); err != nil {
			return xerrors.Errorf("failed to write cid field v: %w", err)
		}

	}

	// t.Indexes (map[string]cid.Cid) (map)
	if len("indexes") > 8192 {
		return xerrors.Errorf("Value in field \"indexes\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("indexes"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("indexes")); err != nil {
		return err
	}

	{
		if len(t.Indexes) > 4096 {
			return xerrors.Errorf("cannot marshal t.Indexes map too large")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajMap, uint64(len(t.Indexes))); err != nil {
			return err
		}

		keys := make([]string, 0, len(t.Indexes))
		for k := range t.Indexes {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			v := t.Indexes[k]

			if len(k) > 8192 {
				return xerrors.Errorf("Value in field k was too long")
			}

			if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(k))); err != nil {
				return err
			}
			if _, err := cw.WriteString(string(k)); err != nil {
				return err
			}

			if err := cbg.WriteCid(cw, v); err != nil {
				return xerrors.Errorf("failed to write cid field v: %w", err)
			}

		}
	}
	return nil
}

func (t *QueryResult0_1) UnmarshalCBOR(r io.Reader) (err error) {
	*t = QueryResult0_1{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("QueryResult0_1: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 7)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Claims ([]cid.Cid) (slice)
		case "claims":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 8192 {
				return fmt.Errorf("t.Claims: array too large (%d)", extra)
			}

			if maj != cbg.MajArray {
				return fmt.Errorf("expected cbor array")
			}

			if extra > 0 {
				t.Claims = make([]cid.Cid, extra)
			}

			for i := 0; i < int(extra); i++ {
				{
					var maj byte
					var extra uint64
					var err error
					_ = maj
					_ = extra
					_ = err

					{

						c, err := cbg.ReadCid(cr)
						if err != nil {
							return xerrors.Errorf("failed to read cid field t.Claims[i]: %w", err)
						}

						t.Claims[i] = c

					}

				}
			}
			// t.Indexes (map[string]cid.Cid) (map)
		case "indexes":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}
			if maj != cbg.MajMap {
				return fmt.Errorf("expected a map (major type 5)")
			}
			if extra > 4096 {
				return fmt.Errorf("t.Indexes: map too large")
			}

			t.Indexes = make(map[string]cid.Cid, extra)

			for i, l := 0, int(extra); i < l; i++ {

				var k string

				{
					sval, err := cbg.ReadStringWithMax(cr, 8192)
					if err != nil {
						return err
					}

					k = string(sval)
				}

				var v cid.Cid

				{

					c, err := cbg.ReadCid(cr)
					if err != nil {
						return xerrors.Errorf("failed to read cid field v: %w", err)
					}

					v = c

				}

				t.Indexes[k] = v

			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
