//go:build !codegen

// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package queryresult

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *QueryResult) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Result0_1 (queryresult.QueryResult0_1) (struct)
	if t.Result0_1 != nil {
		if len("index/query/result@0.1") > 8192 {
			return fmt.Errorf("string in field \"index/query/result@0.1\" was too long")
		}
		if err := jw.WriteString(string("index/query/result@0.1")); err != nil {
			return fmt.Errorf("writing string for field \"index/query/result@0.1\": %w", err)
		}
		if err := jw.WriteObjectColon(); err != nil {
			return err
		}
		if err := t.Result0_1.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("marshaling field t.Result0_1: %w", err)
		}
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *QueryResult) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = QueryResult{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for QueryResult: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for QueryResult: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for QueryResult: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field QueryResult: string too large")
				}
				return fmt.Errorf("reading string for field QueryResult: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field QueryResult: %w", err)
			}
			switch name {

			// t.Result0_1 (queryresult.QueryResult0_1) (struct)
			case "index/query/result@0.1":

				{
					null, err := jr.PeekNull()
					if err != nil {
						return fmt.Errorf("peeking null for field t.Result0_1: %w", err)
					}
					if null {
						if err := jr.ReadNull(); err != nil {
							return fmt.Errorf("reading null for field t.Result0_1: %w", err)
						}
					} else {
						t.Result0_1 = new(QueryResult0_1)
						if err := t.Result0_1.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling t.Result0_1 pointer: %w", err)
						}
					}
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for QueryResult: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field QueryResult: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for QueryResult")
			}
		}
	}

	return nil
}
func (t *QueryResult0_1) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Claims ([]cid.Cid) (slice)
	if len("claims") > 8192 {
		return fmt.Errorf("string in field \"claims\" was too long")
	}
	if err := jw.WriteString(string("claims")); err != nil {
		return fmt.Errorf("writing string for field \"claims\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Claims) > 8192 {
		return fmt.Errorf("slice value in field t.Claims was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Claims: %w", err)
	}
	for i, v := range t.Claims {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Claims: %w", err)
			}
		}

		if err := jw.WriteCid(v); err != nil {
			return fmt.Errorf("writing CID for field v: %w", err)
		}

	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Claims: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Indexes (map[string]cid.Cid) (map)
	if len("indexes") > 8192 {
		return fmt.Errorf("string in field \"indexes\" was too long")
	}
	if err := jw.WriteString(string("indexes")); err != nil {
		return fmt.Errorf("writing string for field \"indexes\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	{
		if len(t.Indexes) > 4096 {
			return fmt.Errorf("cannot marshal t.Indexes map too large")
		}

		if err := jw.WriteObjectOpen(); err != nil {
			return fmt.Errorf("writing object open for field t.Indexes: %w", err)
		}

		keys := make([]string, 0, len(t.Indexes))
		for k := range t.Indexes {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for i, k := range keys {
			if i > 0 {
				if err := jw.WriteComma(); err != nil {
					return fmt.Errorf("writing comma for field t.Indexes: %w", err)
				}
			}
			v := t.Indexes[k]
			if len(k) > 8192 {
				return fmt.Errorf("string in field k was too long")
			}
			if err := jw.WriteString(string(k)); err != nil {
				return fmt.Errorf("writing string for field k: %w", err)
			}
			if err := jw.WriteObjectColon(); err != nil {
				return fmt.Errorf("writing colon for field t.Indexes: %w", err)
			}

			if err := jw.WriteCid(v); err != nil {
				return fmt.Errorf("writing CID for field v: %w", err)
			}

		}
		if err := jw.WriteObjectClose(); err != nil {
			return fmt.Errorf("writing object close for field t.Indexes: %w", err)
		}
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *QueryResult0_1) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = QueryResult0_1{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for QueryResult0_1: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for QueryResult0_1: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for QueryResult0_1: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field QueryResult0_1: string too large")
				}
				return fmt.Errorf("reading string for field QueryResult0_1: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field QueryResult0_1: %w", err)
			}
			switch name {

			// t.Claims ([]cid.Cid) (slice)
			case "claims":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Claims: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Claims: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Claims: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]cid.Cid, 1)
							{

								c, err := jr.ReadCid()
								if err != nil {
									return fmt.Errorf("reading CID for field item[0]: %w", err)
								}
								item[0] = c

							}
							t.Claims = append(t.Claims, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Claims: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Claims: slice too large")
							}
						}
					}

				}

				// t.Indexes (map[string]cid.Cid) (map)
			case "indexes":
				if err := jr.ReadObjectOpen(); err != nil {
					return fmt.Errorf("reading object open for field t.Indexes: %w", err)
				}

				t.Indexes = map[string]cid.Cid{}

				close, err := jr.PeekObjectClose()
				if err != nil {
					return fmt.Errorf("peeking object close for field t.Indexes: %w", err)
				}
				if close {
					if err := jr.ReadObjectClose(); err != nil {
						return fmt.Errorf("reading object close for field t.Indexes: %w", err)
					}
				} else {
					for i, l := 0, 8192; i < l; i++ {
						var k string
						{
							sval, err := jr.ReadString(8192)
							if err != nil {
								if errors.Is(err, jsg.ErrLimitExceeded) {
									return fmt.Errorf("reading string for field k: string too long")
								}
								return fmt.Errorf("reading string for field k: %w", err)
							}
							k = string(sval)
						}
						if err := jr.ReadObjectColon(); err != nil {
							return fmt.Errorf("reading object colon for field t.Indexes: %w", err)
						}
						var v cid.Cid
						{

							c, err := jr.ReadCid()
							if err != nil {
								return fmt.Errorf("reading CID for field v: %w", err)
							}
							v = c

						}
						t.Indexes[k] = v
						close, err := jr.ReadObjectCloseOrComma()
						if err != nil {
							return fmt.Errorf("reading object close or comma for field t.Indexes: %w", err)
						}
						if close {
							break
						}
					}
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for QueryResult0_1: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field QueryResult0_1: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for QueryResult0_1")
			}
		}
	}

	return nil
}
