<%
if [[ "$TF_WORKSPACE" == "prod" || "$TF_WORKSPACE" == "forge-prod" || "$TF_WORKSPACE" == "forge-test" || ${TF_VAR_use_prod_vars:-""} == "true" ]]; then
  PROVIDERS_CACHE_EXPIRATION_SECONDS=$((30 * 24 * 60 * 60))
  NO_PROVIDERS_CACHE_EXPIRATION_SECONDS=$((24 * 60 * 60))
  INDEXES_CACHE_EXPIRATION_SECONDS=$((24 * 60 * 60))
  CLAIMS_CACHE_EXPIRATION_SECONDS=$((7 * 24 * 60 * 60))
  GOLOG_LOG_LEVEL="error"
  BASE_TRACE_SAMPLE_RATIO="0.0001"
else
  PROVIDERS_CACHE_EXPIRATION_SECONDS=$((24 * 60 * 60))
  NO_PROVIDERS_CACHE_EXPIRATION_SECONDS=$((60 * 60))
  INDEXES_CACHE_EXPIRATION_SECONDS=$((60 * 60))
  CLAIMS_CACHE_EXPIRATION_SECONDS=$((24 * 60 * 60))
  GOLOG_LOG_LEVEL="debug"
  BASE_TRACE_SAMPLE_RATIO="1.0"
fi

# Set up telemetry
if [[ -z "${TELEMETRY_DISABLED-}" ]]; then
  if [[ -n "${HONEYCOMB_API_KEY-}" ]]; then
    # HONEYCOMB_API_KEY set, send telemetry to Honeycomb
    OTEL_SERVICE_NAME="${TF_WORKSPACE}-${TF_VAR_app}"
    OTEL_EXPORTER_OTLP_ENDPOINT=https://api.honeycomb.io:443
    OTEL_EXPORTER_OTLP_HEADERS="x-honeycomb-team=${HONEYCOMB_API_KEY}"
  else
    # HONEYCOMB_API_KEY not set, use Storacha's OTEL collector
    OTEL_SERVICE_NAME="${TF_WORKSPACE}-${TF_VAR_app}"
    OTEL_EXPORTER_OTLP_ENDPOINT=https://telemetry.storacha.network:443
    OTEL_EXPORTER_OTLP_HEADERS=""
  fi
fi

%>

PROVIDERS_CACHE_EXPIRATION_SECONDS=<%= $PROVIDERS_CACHE_EXPIRATION_SECONDS %>
NO_PROVIDERS_CACHE_EXPIRATION_SECONDS=<%= $NO_PROVIDERS_CACHE_EXPIRATION_SECONDS %>
INDEXES_CACHE_EXPIRATION_SECONDS=<%= $INDEXES_CACHE_EXPIRATION_SECONDS %>
CLAIMS_CACHE_EXPIRATION_SECONDS=<%= $CLAIMS_CACHE_EXPIRATION_SECONDS %>

IPNI_ENDPOINT=<%= ${IPNI_ENDPOINT:-""} %>
IPNI_FALLBACK_ENDPOINTS=<%= ${IPNI_FALLBACK_ENDPOINTS:-""} %>
IPNI_ANNOUNCE_URLS=<%= ${IPNI_ANNOUNCE_URLS:-""} %>
IPNI_FORMAT_PEER_ID=<%= ${IPNI_FORMAT_PEER_ID:-""} %>
IPNI_FORMAT_ENDPOINT=<%= ${IPNI_FORMAT_ENDPOINT:-""} %>

GOLOG_LOG_LEVEL=<%= $GOLOG_LOG_LEVEL %>

TELEMETRY_DISABLED=<%= ${TELEMETRY_DISABLED:-""} %>
OTEL_SERVICE_NAME=<%= ${OTEL_SERVICE_NAME:-""} %>
OTEL_EXPORTER_OTLP_ENDPOINT=<%= ${OTEL_EXPORTER_OTLP_ENDPOINT:-""} %>
OTEL_EXPORTER_OTLP_HEADERS=<%= ${OTEL_EXPORTER_OTLP_HEADERS:-""} %>
BASE_TRACE_SAMPLE_RATIO=<%= $BASE_TRACE_SAMPLE_RATIO %>

SENTRY_DSN=<%= ${SENTRY_DSN:-""} %>
SENTRY_ENVIRONMENT=<%= ${SENTRY_ENVIRONMENT:-""} %>